function N = N(eta,xi,zeta)
%N
%    N = N(ETA,XI,ZETA)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    05-Mar-2022 03:21:15

t2 = eta+1.0;
t3 = eta.^2;
t4 = xi.^2;
t5 = zeta+1.0;
t6 = zeta.^2;
t7 = eta-1.0;
t8 = -xi;
t9 = -zeta;
t10 = zeta-1.0;
t11 = xi./4.0;
t14 = xi./8.0;
t12 = t3-1.0;
t13 = t6-1.0;
t15 = t4./4.0;
t16 = t11+1.0./4.0;
t17 = t11-1.0./4.0;
t18 = t14+1.0./8.0;
t19 = t14-1.0./8.0;
t20 = t15-1.0./4.0;
N = [t7.*t10.*t19.*(t2+t5+xi);-t7.*t10.*t18.*(t2+t5+t8);-t2.*t10.*t18.*(-t5+t7+xi);-t2.*t10.*t19.*(t5-t7+xi);-t5.*t7.*t19.*(t2+t9+xi+1.0);t5.*t7.*t18.*(t2+t8+t9+1.0);t2.*t5.*t18.*(t7+t10+xi);-t2.*t5.*t19.*(t7+t8+t10);-t7.*t10.*t20;t10.*t12.*t16;t2.*t10.*t20;-t10.*t12.*t17;t5.*t7.*t20;-t5.*t12.*t16;-t2.*t5.*t20;t5.*t12.*t17;-t7.*t13.*t17;t7.*t13.*t16;-t2.*t13.*t16;t2.*t13.*t17];
